### ISSUE TITLE
error in MacOS serria(10.12)

### ISSUE THREAD

**Issue by qiuzhu** [MiKTeX/homebrew-miktex#1]
I use brew to install miktex in Mac ,but when I type tex (miktex、xelatex、pdflatex
）in cmd ,but there is no such command , and i type the mpm -- list, the error is :+1:
log4cxx: No appender could be found for logger (mpmcli).
log4cxx: Please initialize the log4cxx system properly.
and I  use latex to compile the tex file , so I configue the pdflatex or xelatex path in my texstudio , when I navigate the miktex installation dir but find no miktex-pdflatex or miktex -xelatex.

**Comment by hebirge** [comment]
Same

**Comment by ll0808050** [comment]
same question

**Comment by serialc** [comment]
In High Sierra, installation of version 2.9.6500 according to [instructions](https://miktex.org/howto/install-miktex-mac) does not provide a functioning latex installation. Commands are not found.

**Comment by edocevoli** [comment]
I cannot reproduce the problem with MiKTeX 2.9.6500. Running `pdflatex sample2e` produces a valid PDF file, so it seems that `pdflatex` works now.
