### ISSUE TITLE
Setting up local package rep. [Problem]

### ISSUE THREAD

**Issue by TahaMagdy** [MiKTeX/homebrew-miktex#13]
Hello there!

macOS Sierra, Version 10.12.6
I have installed `miktex` from brew.
I am trying to set up my local package repository, using this:
`miktexsetup --verbose --local-package-repository=~/miktex_packages --package-set=complete download`

I get:
`miktexsetup: MiKTeX encountered an internal error.`

**Comment by edocevoli** [comment]
I need more info (log files, screen output).

**Comment by TahaMagdy** [comment]
Actually, I have just installed it, then I followed the documentation so that I have a local rep.
So there is no log file yet, and the only screen out put is this: `miktexsetup: MiKTeX encountered an internal error.`

But `mpm` works well,  If you could help me to install the basic or the complete packages though `mpm`, It will be helpful.


Thank You
