### ISSUE TITLE
Miktex tap is causing a breaking error in homebrew

### ISSUE THREAD

**Issue by raikesy** [MiKTeX/homebrew-miktex#16]
Since running `brew update` today, this error was thrown:
```
Error: Calling needs :cxx14 is disabled! There is no replacement.
Please report this to the miktex/miktex tap:
  /usr/local/Homebrew/Library/Taps/miktex/homebrew-miktex/Formula/miktex.rb:40

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/miktex/homebrew-miktex/issues
```
This also breaks other homebrew commands including `brew outdated` and `brew doctor`.

Other taps seem to have a similar issue: phpv8/homebrew-tap#4

Currently I have had to untap miktex/miktex to stop the error breaking homebrew

**Comment by edocevoli** [comment]
The formula hasn't been updated for a while. And I have no plans to release a new version.
