### ISSUE TITLE
dyld: Library not loaded & miktex & brew & sierra 10.12.6

### ISSUE THREAD

**Issue by agnoicon** [MiKTeX/homebrew-miktex#2]
# Check list

- [ X] Ran `brew update`
- [ X] Ran `brew outdated miktex || brew upgrade miktex`
- [ X] Checked the log files in `~/.miktex/data/miktex/log`
- [ X] Checked the log files in `/usr/local/var/cache/miktex-texmf/miktex/log`

# Bug report
I'm using TeXstudio 2.12.6 , when I tried to build a pdf file from a tex file it crased with the following error:

**dyld: Library not loaded: /usr/local/opt/poppler/lib/libpoppler.68.dylib Referenced from: /usr/local/bin/pdflatex Reason: image not found**

Error: Command crashed: pdflatex -synctex=1 -interaction=nonstopmode "file".tex

## What I tried to do

Uninstall and reinstalling and updating: cairo, poppler, miktex and TeXstudio through brew 
Even I tested it in the command line:

$ /usr/local/bin/miktex-pdflatex
dyld: Library not loaded: /usr/local/opt/poppler/lib/libpoppler.68.dylib
  Referenced from: /usr/local/bin/miktex-pdflatex
  Reason: image not found
Abort trap: 6

Poppler version is 0.59.0_1 & miktex 2.9.6420
But everything failed, there is no way I can solved this issue .

**Comment by edocevoli** [comment]
MiKTeX 2.9.6500 now uses an internal poppler library.
