### ISSUE TITLE
Miktex install error symbols not found for architecture x86_64

### ISSUE THREAD

**Issue by StefanBohr** [MiKTeX/homebrew-miktex#4]
# Bug report

Miktex install error during brew install miktex

## My check list

- [x] Ran `brew update`
- [x] Ran `brew outdated miktex || brew upgrade miktex`
- [x] Checked the log files in `~/.miktex/texmfs/data/miktex/log`
- [x] Checked the log files in `/usr/local/var/cache/miktex-texmf/miktex/log`

## What I tried to do
brew install miktex from shell via  
brew install miktex

## What I expected to happen
Just installation/update of miktex

## What happened instead
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/miktex/02.make:
  "_FT_Init_FreeType", referenced from:
      CairoOutputDev::CairoOutputDev() in CairoOutputDev.cc.o
  "_FT_Library_Version", referenced from:
      CairoFontEngine::CairoFontEngine(FT_LibraryRec_*) in CairoFontEngine.cc.o
  "_FT_New_Face", referenced from:
      _ft_new_face_uncached(FT_LibraryRec_*, char const*, char*, int, FT_FaceRec_**, _cairo_font_face**) in CairoFontEngine.cc.o
  "_FT_New_Memory_Face", referenced from:
      _ft_new_face(FT_LibraryRec_*, char const*, char*, int, FT_FaceRec_**, _cairo_font_face**) in CairoFontEngine.cc.o
      _ft_new_face_uncached(FT_LibraryRec_*, char const*, char*, int, FT_FaceRec_**, _cairo_font_face**) in CairoFontEngine.cc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sandbox/miktex/bin/darwin-x86_64/miktex-pdftocairo] Error 1
make[1]: *** [Libraries/3rd/poppler/utils/CMakeFiles/miktex-pdftocairo.dir/all] Error 2
[ 46%] Built target miktex-pdfinfo
make: *** [all] Error 2

**Comment by edocevoli** [comment]
Is this on a "Sierra" or "High Sierra" Mac?

**Comment by StefanBohr** [comment]
It is on "High Sierra", 10.13 with latest (standard) updates.

**Comment by edocevoli** [comment]
Thank you. 10.13 is not yet supported by Homebrew, it seems.
