### ISSUE TITLE
Error Installing MikTeX

### ISSUE THREAD

**Issue by iamavidlearner** [MiKTeX/homebrew-miktex#5]
> curl: (7) Failed to connect to cmake.org port 443: Operation timed out Error: Failed to download resource "cmake" Download failed: https://cmake.org/files/v3.9/cmake-3.9.6.tar.gz

Followed the instructions given on the [https://miktex.org/howto/install-miktex-mac](url)
When the command `brew install miktex` is ran, the above error shows.
OS X Yosemite

**Comment by edocevoli** [comment]
This is not a MiKTeX related issue.
